name: Deploy every 4 hours

on:
  schedule:
    # Toutes les 4 heures
    - cron: "0 */4 * * *"
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # adapte selon ton projet

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start
